---
- name: "Stop Postgres Service To Load New Configuration"
  ansible.builtin.systemd:
    name: "postgresql@16-main.service"
    state: stopped
    no_block: false # wait for clean stop

- name: "Start Postgres Service To Load New Configuration"
  ansible.builtin.systemd:
    name: "postgresql@16-main.service"
    enabled: true
    state: started
    no_block: false
